config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :users, only: :create
  resources :comments, only: :create

  resources :rooms do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :room
  belongs_to :user

  validates :content, presence: true
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :room
  belongs_to :user

  validates :content, presence: true

  after_create_commit { broadcast_append_to self.room }
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages
  has_many :comments

  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end

  def increment_views_count
    self.views += 1
    save
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :messages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(content: comment_params[:content], room_id: params[:format])

    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_to rooms_path, alert: 'Erro ao criar o comentário.'
    end
  end

  private

  def comment_params
    params.permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = current_user.messages.create(content: message_params[:content], room_id: params[:room_id])
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show ]

  # GET /rooms or /rooms.json
  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @room.increment_views_count
    @message = Message.new
    @comments = @room.comments.order(id: :desc)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_url, notice: 'Sala criada com sucesso.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name, :video_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    @user.save
    session[:user_id] = @user.id

    redirect_to room_url(params[:room_id])
  end

  private

  def user_params
    params.permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_messages
    flash_messages = []

    flash.each do |key, value|
      if key == 'notice'
        flash_messages << "<div class='alert alert-success alert-dismissible fade show' role='alert'>#{value}<button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button></div>"
      elsif key == 'alert'
        flash_messages << "<div class='alert alert-danger alert-dismissible fade show' role='alert'>#{value}<button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button></div>"
      end
    end

    flash_messages.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
  <div class="comment">
    <h4><%= comment.user.username %></h4>
    <p><%= comment.content %></p>
    <span class="timestamp"><%= comment.created_at.strftime("%d/%m/%Y %H:%M") %></span>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(url: comments_path(@room), method: :post, remote: true) do |form| %>
  <%= form.text_area :content, class: "form-control", placeholder: "Digite o seu comentário", required: true %>
  <%= form.submit "Enviar", class: "btn btn-primary mt-2" %>
<% end %>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center mt-5">
      <h1>Bem-vindo ao Meu Sistema!</h1>
      <p class="lead">Este é um teste de conhecimento de Ruby on Rails.</p>
      <p>Comece a explorar as funcionalidades disponíveis na barra de navegação.</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoWatchParty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <%= render partial: "messages/sender_message" %>
  <body>
    <%= render partial: "shared/navbar" %>

    <div class="container mt-4">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="mt-auto">
  <%= form_with(model: [@room, @message], remote: true) do |f| %>
    <div class="input-group">
      <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off', placeholder: "Digite sua mensagem" %>
      <div class="input-group-append">
        <%= f.submit data: { disable_with: false }, class: "btn btn-primary ms-2", value: "Enviar" %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<div class="chat-message other-<%= message.user.id %> current-<%= message.user.id %>">
  <h6 class="name"> <%= message.user.username %> </h6>
  <%= message.content %>
</div>

app/views/messages/_sender_message.html.erb
<style>
  <%= ".current-#{current_user&.id}" %> {
      background-color: #DCF8C6 !important;
      padding: 10px;

  }
  <%= ".other-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
  }
</style>

app/views/rooms/_form.html.erb
<%= form_with(model: room, class: 'mt-4') do |form| %>

<div class="mb-3">
  <%= form.label :name, class: 'form-label' %>
  <%= form.text_field :name, class: 'form-control' %>
</div>

<div class="mb-3">
  <%= form.label :video_url, class: 'form-label' %>
  <%= form.text_field :video_url, class: 'form-control' %>
</div>

<div class="alert alert-info">
  Adicione um link do Youtube copiado do navegador no campo acima.
</div>

<%= form.submit 'Criar Sala', class: 'btn btn-primary' %>
<% end %>

app/views/rooms/_room.html.erb
<%= stylesheet_link_tag('rooms') %>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2 class="text-center mt-4"><%= @room.name %></h2>
      <div class="video-container">
        <div class="embed-responsive embed-responsive-16by9 youtube-video">
          <iframe width="560" height="315" src="//www.youtube.com/embed/<%= YouTubeRails.extract_video_id(@room.video_url) %>" allowfullscreen></iframe>
          <div class="card-body">
            <h6 class="card-title">Visualizações: <%= @room.views %></h6>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <h4 class="text-center mt-4">Chat</h4>
      <div class="chat-container card-body d-flex flex-column shadow-sm p-3 mb-5 bg-body rounded" >
        <%= turbo_stream_from @room %>
        <div id="messages"></div>
        <%= render partial: 'messages/form' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <h4 class="text-center mt-4">Comentários</h4>
      <div class="comment-container shadow-sm p-3 mb-5">
        <%= render partial: 'comments/form' %>
        <br>
        <%= render partial: 'comments/comment' %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_username_modal.html.erb
<% @rooms.each do |room| %>
  <div class="modal fade" id="modal-<%= room.id %>" tabindex="-1" role="dialog" aria-labelledby="modal-label-<%= room.id %>" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal-label-<%= room.id %>">Digite seu nome para entrar na sala</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= form_with(url: users_path, method: :post, remote: true) do |form| %>
            <div class="form-group">
              <%= form.hidden_field :room_id, :value => room.id %>
              <%= form.label :username, "Nome" %>
              <%= form.text_field :username, class: "form-control", required: true %>
            </div>
            <%= form.submit "Entrar", class: "btn btn-primary mt-2" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/index.html.erb
<div class="container">
  <h1>Salas</h1>

  <div class="row mb-3">
    <div class="col-12 col-md-6">
      <%= search_form_for @q, class: "d-flex" do |f| %>
        <%= f.text_field :name_cont, class: "form-control me-2", placeholder: "Buscar por nome da sala..." %>
        <%= button_tag type: :submit, class: "btn btn-outline-success" do %>
          Pesquisar
        <% end %>
        <%= link_to rooms_path, class: "btn btn-outline-secondary ms-2" do %>
          Limpar
        <% end %>
      <% end %>
    </div>
    <div class="col-12 col-md-6">
      <%= link_to "Criar Nova Sala", new_room_path, class: "btn btn-primary float-end" %>
    </div>
  </div>

  <div class="row">
    <% @rooms.each do |room| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="embed-responsive embed-responsive-16by9">
  <!--          <iframe class="embed-responsive-item" src="//i.ytimg.com/vi/<%#= YouTubeRails.extract_video_id(room.video_url)%>/hqdefault.jpg"></iframe>-->
          </div>
          <img src="//i.ytimg.com/vi/<%= YouTubeRails.extract_video_id(room.video_url)%>/hqdefault.jpg" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title"><%= room.name %></h5>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modal-<%= room.id %>">
              Entrar
            </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: "username_modal" %>

app/views/rooms/new.html.erb
<div class="container">
  <h2 class="text-center">Criar Sala</h2>

  <%= render "form", room: @room %>
  <br>
  <%= link_to "Voltar para as salas", rooms_path %>
</div>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Início</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Salas", rooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>